// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcCLq8h3QTa2ZXWVBmvDjg48q9rY_9eJs',
    appId: '1:439649205142:web:f5129ed5efeb8025cd3bb7',
    messagingSenderId: '439649205142',
    projectId: 'project-2-68a89',
    authDomain: 'project-2-68a89.firebaseapp.com',
    storageBucket: 'project-2-68a89.firebasestorage.app',
    measurementId: 'G-GVW359TGLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDFK5R4wAJqYNQKie-XyEHqpNF_4ENw5Y',
    appId: '1:439649205142:android:ba0a288ecc8f7273cd3bb7',
    messagingSenderId: '439649205142',
    projectId: 'project-2-68a89',
    storageBucket: 'project-2-68a89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPIztRUP0SLgUVvoqdlGAQgZbqRz-DiY0',
    appId: '1:439649205142:ios:a92dfe54f86c7073cd3bb7',
    messagingSenderId: '439649205142',
    projectId: 'project-2-68a89',
    storageBucket: 'project-2-68a89.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPIztRUP0SLgUVvoqdlGAQgZbqRz-DiY0',
    appId: '1:439649205142:ios:a92dfe54f86c7073cd3bb7',
    messagingSenderId: '439649205142',
    projectId: 'project-2-68a89',
    storageBucket: 'project-2-68a89.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcCLq8h3QTa2ZXWVBmvDjg48q9rY_9eJs',
    appId: '1:439649205142:web:877c8fabb4907639cd3bb7',
    messagingSenderId: '439649205142',
    projectId: 'project-2-68a89',
    authDomain: 'project-2-68a89.firebaseapp.com',
    storageBucket: 'project-2-68a89.firebasestorage.app',
    measurementId: 'G-D85V4Z0J08',
  );

}